import { MOCK_CITATIONS, SORTED_CITATIONS, MOCK_DOCUMENT, STATUS_META } from "@/lib/mock-citations";
import type { CitationStatus } from "@/lib/mock-citations";
import { Logo } from "./Logo";

const ORDER: CitationStatus[] = ["risk", "mischar", "review", "verified"];

export function ReportView() {
  const score = Math.round(
    MOCK_CITATIONS.reduce((s, c) => s + c.confidence, 0) / MOCK_CITATIONS.length,
  );
  const risky = MOCK_CITATIONS.filter((c) => c.status === "risk").length;
  const mischar = MOCK_CITATIONS.filter((c) => c.status === "mischar").length;
  const verdict =
    risky > 0
      ? "DO NOT FILE WITHOUT REVIEW"
      : mischar > 0
        ? "PARTNER REVIEW REQUIRED"
        : "SAFE TO RELY ON";

  return (
    <article className="mx-auto max-w-3xl rounded-2xl border bg-card p-10 shadow-elegant print:border-0 print:shadow-none">
      <header className="flex items-start justify-between border-b pb-6">
        <div>
          <Logo />
          <p className="mt-3 text-[11px] uppercase tracking-wider text-muted-foreground">
            Citation Verification Report
          </p>
          <h1 className="mt-1 font-display text-3xl text-navy">{MOCK_DOCUMENT.name}</h1>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <p>{MOCK_DOCUMENT.uploadedAt}</p>
          <p>{MOCK_DOCUMENT.jurisdiction}</p>
          <p>{MOCK_DOCUMENT.model}</p>
        </div>
      </header>

      <section className="mt-8 rounded-xl border bg-muted/40 p-6">
        <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
          Verdict
        </p>
        <p className="mt-1 font-display text-3xl text-navy">{verdict}</p>
        <p className="mt-3 text-sm leading-relaxed text-slate-ink">
          Overall trust score <strong className="text-navy">{score}%</strong>. {risky} citation
          {risky === 1 ? "" : "s"} could not be verified and appear{risky === 1 ? "s" : ""} to be
          hallucinated; {mischar} authorit{mischar === 1 ? "y is" : "ies are"} materially
          mischaracterised in the argument as drafted.
        </p>
      </section>

      {ORDER.map((status) => {
        const items = SORTED_CITATIONS.filter((c) => c.status === status);
        if (!items.length) return null;
        return (
          <section key={status} className="mt-8">
            <h2 className="font-display text-xl text-navy">
              {STATUS_META[status].label} ({items.length})
            </h2>
            <p className="text-xs text-muted-foreground">{STATUS_META[status].description}</p>
            <ul className="mt-4 divide-y border-y">
              {items.map((c) => (
                <li key={c.id} className="py-4">
                  <div className="flex items-baseline justify-between gap-4">
                    <div>
                      <p className="font-medium text-navy">{c.caseName}</p>
                      <p className="font-mono text-xs text-muted-foreground">{c.citation}</p>
                    </div>
                    <span className="text-xs tabular-nums text-slate-ink">
                      {c.confidence}% confidence
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-relaxed text-foreground">
                    <strong className="text-navy">Recommended action:</strong> {c.recommendation}
                  </p>
                </li>
              ))}
            </ul>
          </section>
        );
      })}

      <footer className="mt-10 border-t pt-6 text-[11px] leading-relaxed text-muted-foreground">
        AI-assisted verification — human legal review remains recommended before court filing.
        Report generated by {MOCK_DOCUMENT.model}. Run ID rel-2026-06-26-0942-bw.
      </footer>
    </article>
  );
}
